language: julia
os:
#  - linux
  - osx
julia:
#  - release
 - 0.5
notifications:
  email: false
after_success:
  - julia -e 'Pkg.clone("https://github.com/JuliaDocs/Documenter.jl")'
  - julia -e 'cd(Pkg.dir("PhyloNetworks")); include(joinpath("docs", "make.jl"))'